FROM cowtwo/androidstudio:finish_installation
LABEL maintainer="cowtwo"

# Note by Cowtwo
# In the future, we should build image based on cowtwo/androidstudio:finish_installation

#++ vim related
RUN apt-get install -y cscope
RUN apt-get install -y exuberant-ctags
RUN apt-get install -y curl
RUN apt-get install -y git
#--



