FROM gem5/gem5

MAINTAINER cowtwo

LABEL Description="Docker image for gem5"

RUN apt-get update

# Install file browser
RUN apt-get install -y nautilus

# Install text editor
RUN apt-get install -y gedit
