FROM ubuntu
MAINTAINER CowTwo

RUN apt-get update && apt-get install -y kwrite
RUN DEBIAN_FRONTEND=noninteractive apt-get install wireshark -y
RUN apt-get install -y shotwell
RUN apt-get install -y vim
RUN apt-get install -y less
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gtkwave
