FROM cowtwo/gem5_build:1.0

MAINTAINER cowtwo

LABEL Description="Docker image for gem5"

RUN apt-get update

# Install file browser
RUN apt-get install -y nautilus

# Install text editor
RUN apt-get install -y gedit

# Note
# Manually install arm cross compiler toolchain and commit to docker image
# Details, please refer to "Cross Compiler" section in GEM5 document in google drive
