FROM cowtwo/omnetpp:1.0_Base

MAINTAINER cowtwo

LABEL Description="Docker image for OMNeT++ Network Simulator"

RUN apt-get update

# Install GDB
RUN apt-get install -y build-essential gdb

# Install ECLIPSE CDT (C/C++ Developing Tool)
RUN apt-get install -y eclipse eclipse-cdt g++


