FROM cowtwo/omnetpp:3.0

MAINTAINER cowtwo

LABEL Description="Docker image for OMNeT++ Network Simulator"

# Rebuild SystemC w/ "-std=c++11" compiler flag to facilitate systemc/omnet integration
RUN cd /cowtwo/systemc-2.3.2/objdir && \
	make clean && \
	../configure --prefix=/usr/local/systemc232 CFLAGS="-std=c++11" CPPFLAGS="-std=c++11"  CXXFLAGS="-std=c++11" && \
	make && \
	make install	

	
	

